### PR TITLE
Generate gogo and protobuf protos; give them distinct canonical package names

### PR DESCRIPTION
**Pull request by jmacd**

### CODE REVIEW

**Review by MatthewDolan — APPROVED** [review]

**Comment by jmacd** [comment]
@rnburn This will break the lightstep-tracer-c++ build but should be easy to repair. I've removed the `third_party` proto includes from the repo, and moved them into a docker image that contains the protoc tools we use (for Go, at least) and has checked-out versions of the proto includes. The goal here is to generate the generated code and check it into lightstep-tracer-common. I know you do not prefer Make and have used Cmake. I'm open to change, but I have zero Cmake experience and although I don't love it, Make and I get along. What do you think?

**Comment by rnburn** [comment]
Could this cause problems if there's a mismatch between the version of the protobuf library installed on the machine building the tracer library and that used to generate the code checked into lightstep-tracer-common?

**Comment by jmacd** [comment]
Yes. I guess we can leave the third_party stuff and not use it for Go.

**Comment by jmacd** [comment]
I'm going to go ahead with my plans for Go, and leave the files in place for C++.

**Pull request merged**
